# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo ITNOA
        
      - name: Cake Action
        # You may pin to the exact commit or the version.
        # uses: cake-build/cake-action@ada1055e59e6ae62905b178090e9636e96e54a35
        uses: cake-build/cake-action@v1.3.0
        with:
          # The name of the task to execute. Note that this argument must be supported by the script.
          target: "Default"
          # The verbosity level with which to run the script. Valid values are: Quiet, Minimal, Normal, Verbose or Diagnostic.
          verbosity: "Diagnostic"
          # Tells Cake to do a dry run of the script.
          dry-run: false
          # The version of Cake to install.
          cake-version: "1.0.0"
          # Flag for if Cake modules should be installed/bootstrapped.
          cake-bootstrap: "build.ps1"
